In [1]:
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv('../datasets/ml_bwi_dataset.csv')

In [3]:
data.shape

(190273, 105)

In [36]:
data = data[data['tot'] == 0]
data.drop(columns=['tot'], inplace=True)
data

,Tnr,Enr,Bnr,Av,Ba,Al_ba,Bs,Bhd,Hoehe,D7,...,bio_10,bio_11,bio_12,bio_13,bio_14,bio_15,bio_16,bio_17,bio_18,bio_19
0,11,2,1,0,10,119.0,1,330,132.0,242.0,...,15.49,-1.81,1640,231,92,0.32,597,294,597,294
1,11,2,2,0,10,139.0,1,540,176.0,365.0,...,15.49,-1.81,1640,231,92,0.32,597,294,597,294
2,11,2,3,0,10,149.0,1,520,261.0,398.0,...,15.49,-1.81,1640,231,92,0.32,597,294,597,294
3,11,2,4,0,10,149.0,1,528,217.0,385.0,...,15.49,-1.81,1640,231,92,0.32,597,294,597,294
4,18,1,1,0,10,150.0,1,750,355.0,578.0,...,12.49,-3.98,2549,330,150,0.28,894,505,894,505
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190268,57557,4,6,0,50,50.0,1,246,248.0,206.0,...,14.89,-2.32,1032,122,57,0.20,321,206,313,233
190269,57557,4,7,0,50,50.0,1,310,260.0,255.0,...,14.89,-2.32,1032,122,57,0.20,321,206,313,233
190270,57557,4,8,0,10,50.0,1,220,214.0,175.0,...,14.89,-2.32,1032,122,57,0.20,321,206,313,233
190271,57557,4,9,0,10,50.0,1,263,246.0,213.0,...,14.89,-2.32,1032,122,57,0.20,321,206,313,233
190272,57557,4,10,0,10,50.0,1,184,212.0,148.0,...,14.89,-2.32,1032,122,57,0.20,321,206,313,233

In [37]:
data.columns.tolist()

['Tnr',
 'Enr',
 'Bnr',
 'Av',
 'Ba',
 'Al_ba',
 'Bs',
 'Bhd',
 'Hoehe',
 'D7',
 'D03',
 'G',
 'VolR',
 'VolR_FAO',
 'VolE',
 'vVolE',
 'N_ha',
 'Stf',
 'StfM',
 'Bhdst1',
 'Bhdst5',
 'Alkl5',
 'GrGr2',
 'jSchael_x',
 'Biom_o',
 'Biom_u',
 'Biov_o',
 'Gexp',
 'GExpKl4',
 'GExpKl8',
 'Gform',
 'Gneig',
 'GneigKl5',
 'natHoe',
 'potNatWg',
 'HoeheNN',
 'hnnSt100',
 'hnnSt250',
 'Zaun',
 'Be',
 'NatNaeheHaupt',
 'NatNaeheLT7cm',
 'ForestType',
 'RAN',
 'Situation',
 'TOT',
 'Kaefer',
 'jSchael_y',
 'aeSchael',
 'Bkl',
 'Ast',
 'AnzSchad',
 'Ruecke',
 'Specht',
 'Pilz',
 'Harz',
 'BestockAb',
 'Al_baDiff',
 'BhdDiff',
 'HoeheDiff',
 'GDiff',
 'VolRDiff',
 'VolEDiff',
 'vVolEDiff',
 'Biom_oDiff',
 'Biom_uDiff',
 'Biov_oDiff',
 'LAND',
 'SOEH_NR',
 'SOEH_KRZ',
 'SOEH_VAR',
 'BODTYP',
 'NAEHR',
 'WASSER',
 'ADepth',
 'NumHTypes',
 'nfk_30',
 'nfk_60',
 'nfk_80',
 'nfk_90',
 'nfk_100',
 'nfk_160',
 'bl',
 'year_first',
 'year_last',
 'bio_1',
 'bio_2',
 'bio_3',
 'bio_4',
 'bio_5',
 'bio_6',
 'bio_7',
 'bio_8',
 'bio_9',
 'bio_10',
 'bio_11',
 'bio_12',
 'bio_13',
 'bio_14',
 'bio_15',
 'bio_16',
 'bio_17',
 'bio_18',
 'bio_19']

In [38]:
def count_na_values(df, column):
    return df[column].isna().sum()

na_count = dict(zip(data.columns, [count_na_values(data, c) for c in data.columns]))
na_count = pd.DataFrame(na_count.items(), columns=['Column', 'NA Count'])

In [39]:
na_count[na_count['NA Count'] > 0]

        Column  NA Count
9           D7      1698
23   jSchael_x       192
26      Biov_o       192
57   Al_baDiff       974
58     BhdDiff       974
59   HoeheDiff       974
60       GDiff       974
61    VolRDiff       974
62    VolEDiff       974
63   vVolEDiff       974
64  Biom_oDiff       974
65  Biom_uDiff       974
66  Biov_oDiff       974
69    SOEH_KRZ      9270
71      BODTYP      9479
73      WASSER     19186

In [40]:
data_cleaned = data.dropna()
data_cleaned.shape

(166791, 104)

In [51]:
data_cleaned

,Tnr,Enr,Bnr,Av,Ba,Al_ba,Bs,Bhd,Hoehe,D7,...,bio_10,bio_11,bio_12,bio_13,bio_14,bio_15,bio_16,bio_17,bio_18,bio_19
0,11,2,1,0,10,119.0,1,330,132.0,242.0,...,15.49,-1.81,1640,231,92,0.32,597,294,597,294
1,11,2,2,0,10,139.0,1,540,176.0,365.0,...,15.49,-1.81,1640,231,92,0.32,597,294,597,294
2,11,2,3,0,10,149.0,1,520,261.0,398.0,...,15.49,-1.81,1640,231,92,0.32,597,294,597,294
3,11,2,4,0,10,149.0,1,528,217.0,385.0,...,15.49,-1.81,1640,231,92,0.32,597,294,597,294
4,18,1,1,0,10,150.0,1,750,355.0,578.0,...,12.49,-3.98,2549,330,150,0.28,894,505,894,505
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190268,57557,4,6,0,50,50.0,1,246,248.0,206.0,...,14.89,-2.32,1032,122,57,0.20,321,206,313,233
190269,57557,4,7,0,50,50.0,1,310,260.0,255.0,...,14.89,-2.32,1032,122,57,0.20,321,206,313,233
190270,57557,4,8,0,10,50.0,1,220,214.0,175.0,...,14.89,-2.32,1032,122,57,0.20,321,206,313,233
190271,57557,4,9,0,10,50.0,1,263,246.0,213.0,...,14.89,-2.32,1032,122,57,0.20,321,206,313,233
190272,57557,4,10,0,10,50.0,1,184,212.0,148.0,...,14.89,-2.32,1032,122,57,0.20,321,206,313,233

In [ ]:
corr_mat = features_continuous.corr().stack().reset_index(name="correlation")